export function initializeDummyData() {
  if (typeof window === "undefined") return

  // Check if data already exists
  if (localStorage.getItem("dataInitialized")) return

  // Dummy Devices
  const devices = [
    {
      id: "DEV001",
      deviceType: "Laptop",
      brand: "Dell",
      modelName: "XPS 15",
      serialNumber: "DXPS15-2024-001",
      assetTag: "AT-L-001",
      purchaseDate: "2024-01-15",
      purchaseCost: 1599.99,
      vendorName: "Dell Direct",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-01-15",
      status: "Available",
      processor: "Intel Core i7-13700H",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      os: "Windows 11 Pro",
      images: [],
      notes: "High-performance laptop for development work",
    },
    {
      id: "DEV002",
      deviceType: "Laptop",
      brand: "Apple",
      modelName: 'MacBook Pro 14"',
      serialNumber: "MBP14-2024-001",
      assetTag: "AT-L-002",
      purchaseDate: "2024-02-10",
      purchaseCost: 2399.99,
      vendorName: "Apple Store",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-02-10",
      status: "Available",
      processor: "Apple M3 Pro",
      ram: "18GB Unified Memory",
      storage: "512GB SSD",
      os: "macOS Sonoma",
      images: [],
      notes: "For design and development teams",
    },
    {
      id: "DEV003",
      deviceType: "Laptop",
      brand: "Lenovo",
      modelName: "ThinkPad X1 Carbon",
      serialNumber: "LTP-X1C-2024-001",
      assetTag: "AT-L-003",
      purchaseDate: "2024-03-05",
      purchaseCost: 1899.99,
      vendorName: "Lenovo Enterprise",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-03-05",
      status: "Available",
      processor: "Intel Core i7-1365U",
      ram: "16GB LPDDR5",
      storage: "1TB NVMe SSD",
      os: "Windows 11 Pro",
      images: [],
      notes: "Ultralight business laptop",
    },
    {
      id: "DEV004",
      deviceType: "Desktop",
      brand: "HP",
      modelName: "EliteDesk 800 G9",
      serialNumber: "HP-ED800-2024-001",
      assetTag: "AT-D-001",
      purchaseDate: "2024-01-20",
      purchaseCost: 1299.99,
      vendorName: "HP Enterprise",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-01-20",
      status: "Available",
      processor: "Intel Core i7-12700",
      ram: "32GB DDR4",
      storage: "1TB NVMe SSD",
      os: "Windows 11 Pro",
      images: [],
      notes: "Office workstation",
    },
    {
      id: "DEV005",
      deviceType: "Desktop",
      brand: "Dell",
      modelName: "OptiPlex 7090",
      serialNumber: "DOP-7090-2024-001",
      assetTag: "AT-D-002",
      purchaseDate: "2024-02-15",
      purchaseCost: 1099.99,
      vendorName: "Dell Direct",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-02-15",
      status: "Available",
      processor: "Intel Core i5-11500",
      ram: "16GB DDR4",
      storage: "512GB SSD",
      os: "Windows 11 Pro",
      images: [],
      notes: "Standard office desktop",
    },
    {
      id: "DEV006",
      deviceType: "Mobile",
      brand: "Apple",
      modelName: "iPhone 15 Pro",
      serialNumber: "IP15P-2024-001",
      assetTag: "AT-M-001",
      purchaseDate: "2024-03-10",
      purchaseCost: 1199.99,
      vendorName: "Apple Store",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-03-10",
      status: "Available",
      imei: "356789012345678",
      storage: "256GB",
      os: "iOS 17",
      images: [],
      notes: "Corporate mobile device",
    },
    {
      id: "DEV007",
      deviceType: "Mobile",
      brand: "Samsung",
      modelName: "Galaxy S24",
      serialNumber: "SGS24-2024-001",
      assetTag: "AT-M-002",
      purchaseDate: "2024-03-15",
      purchaseCost: 899.99,
      vendorName: "Samsung Direct",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-03-15",
      status: "Available",
      imei: "356789012345679",
      storage: "128GB",
      os: "Android 14",
      images: [],
      notes: "Android mobile device",
    },
    {
      id: "DEV008",
      deviceType: "Mobile",
      brand: "Google",
      modelName: "Pixel 8 Pro",
      serialNumber: "GP8P-2024-001",
      assetTag: "AT-M-003",
      purchaseDate: "2024-03-20",
      purchaseCost: 999.99,
      vendorName: "Google Store",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-03-20",
      status: "Available",
      imei: "356789012345680",
      storage: "256GB",
      os: "Android 14",
      images: [],
      notes: "Premium Android device",
    },
    {
      id: "DEV009",
      deviceType: "Tablet",
      brand: "Apple",
      modelName: 'iPad Pro 12.9"',
      serialNumber: "IPP-129-2024-001",
      assetTag: "AT-T-001",
      purchaseDate: "2024-02-20",
      purchaseCost: 1299.99,
      vendorName: "Apple Store",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-02-20",
      status: "Available",
      storage: "256GB",
      os: "iPadOS 17",
      images: [],
      notes: "For presentations and field work",
    },
    {
      id: "DEV010",
      deviceType: "Tablet",
      brand: "Samsung",
      modelName: "Galaxy Tab S9",
      serialNumber: "SGT-S9-2024-001",
      assetTag: "AT-T-002",
      purchaseDate: "2024-02-25",
      purchaseCost: 799.99,
      vendorName: "Samsung Direct",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-02-25",
      status: "Available",
      storage: "128GB",
      os: "Android 14",
      images: [],
      notes: "Android tablet for various tasks",
    },
    {
      id: "DEV011",
      deviceType: "Peripheral",
      brand: "Dell",
      modelName: 'UltraSharp 27" Monitor',
      serialNumber: "DU27-2024-001",
      assetTag: "AT-P-001",
      purchaseDate: "2024-01-10",
      purchaseCost: 449.99,
      vendorName: "Dell Direct",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2027-01-10",
      status: "Available",
      images: [],
      notes: "4K display for workstations",
    },
    {
      id: "DEV012",
      deviceType: "Peripheral",
      brand: "Logitech",
      modelName: "MX Master 3S",
      serialNumber: "LMX3S-2024-001",
      assetTag: "AT-P-002",
      purchaseDate: "2024-01-15",
      purchaseCost: 99.99,
      vendorName: "Logitech",
      warrantyStatus: "Valid",
      warrantyExpiryDate: "2025-01-15",
      status: "Available",
      images: [],
      notes: "Wireless mouse",
    },
  ]

  // Dummy Employees
  const employees = [
    {
      id: "EMP001",
      name: "John Doe",
      email: "john.doe@antheminfotech.com",
      phone: "+1 (555) 123-4567",
      department: "Engineering",
      designation: "Senior Software Engineer",
      hireDate: "2022-01-15",
      status: "Active",
    },
    {
      id: "EMP002",
      name: "Jane Smith",
      email: "jane.smith@antheminfotech.com",
      phone: "+1 (555) 234-5678",
      department: "Engineering",
      designation: "Frontend Developer",
      hireDate: "2022-03-20",
      status: "Active",
    },
    {
      id: "EMP003",
      name: "Mike Johnson",
      email: "mike.johnson@antheminfotech.com",
      phone: "+1 (555) 345-6789",
      department: "Design",
      designation: "UI/UX Designer",
      hireDate: "2022-06-10",
      status: "Active",
    },
    {
      id: "EMP004",
      name: "Sarah Williams",
      email: "sarah.williams@antheminfotech.com",
      phone: "+1 (555) 456-7890",
      department: "Product",
      designation: "Product Manager",
      hireDate: "2021-11-05",
      status: "Active",
    },
    {
      id: "EMP005",
      name: "David Brown",
      email: "david.brown@antheminfotech.com",
      phone: "+1 (555) 567-8901",
      department: "Engineering",
      designation: "Backend Developer",
      hireDate: "2023-01-12",
      status: "Active",
    },
  ]

  // Store in localStorage
  localStorage.setItem("devices", JSON.stringify(devices))
  localStorage.setItem("employees", JSON.stringify(employees))
  localStorage.setItem("assignments", JSON.stringify([]))
  localStorage.setItem("dataInitialized", "true")
}
